[package]
name = "storystream-resilience"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2.0.17"
tokio = { version = "1.42", features = ["time", "sync"] }