name: CI
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }
  workflow_dispatch:
permissions: { contents: read }
jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo CI OK
