# .github/workflows/promote.yml
# Auto-PRs to move code through YOUR flow:
# first-dev → stage-7-security → stage-9-final → main
name: storystream-promotions

on:
  push:
    branches:
      - first-dev
      - stage-7-security
      - stage-9-final
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: promote-${{ github.ref }}
  cancel-in-progress: true

jobs:
  to-stage7:
    if: github.ref == 'refs/heads/first-dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Open/Update PR first-dev → stage-7-security
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote: first-dev → stage-7-security"
          body: |
            Auto-promotion from **first-dev** to **stage-7-security**.
            This PR will auto-merge when required checks pass.
          base: stage-7-security
          branch: promote/first-dev-to-stage7
          labels: ci, auto-promotion
          draft: false
          update-branch: true

      - name: Enable automerge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

  to-stage9:
    if: github.ref == 'refs/heads/stage-7-security'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Open/Update PR stage-7-security → stage-9-final
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote: stage-7-security → stage-9-final"
          body: "Promotion gated by CI success on **stage-7-security**."
          base: stage-9-final
          branch: promote/stage7-to-stage9
          labels: ci, auto-promotion
          draft: false
          update-branch: true

      - name: Enable automerge (rebase)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase

  to-main:
    if: github.ref == 'refs/heads/stage-9-final'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Open/Update PR stage-9-final → main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Promote: RC → main"
          body: "Final promotion into **main**. Approval may be required depending on repo settings."
          base: main
          branch: promote/stage9-to-main
          labels: ci, release
          draft: false
          update-branch: true

      - name: Enable automerge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
