# .github/workflows/rust-ci.yml
# A lightweight duplicate CI that only runs on PRs to the mainline branches.
# Keeps PR noise down while still validating Rust builds.
name: Rust CI (PR focus)

on:
  pull_request:
    branches:
      - main
      - stage-*
      - first-dev
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: rust-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  check-and-test:
    name: Check & Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: rustfmt check
        run: cargo fmt --all -- --check

      - name: clippy (deny warnings)
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

      - name: Build
        run: cargo build --workspace --all-features --all-targets

      - name: Test
        run: cargo test --workspace --all-features -- --nocapture

      - name: Upload test reports (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rust-test-output
          path: target
          if-no-files-found: ignore
